# Generated by Django 5.2.3 on 2025-06-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мобильный')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('specialties', models.TextField(blank=True, null=True, verbose_name='Специализации')),
                ('property_types', models.TextField(blank=True, null=True, verbose_name='Типы недвижимости')),
                ('markets', models.TextField(blank=True, null=True, verbose_name='Рынки')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('affiliations', models.TextField(blank=True, null=True, verbose_name='Членство в организациях')),
                ('profile_url', models.URLField(max_length=1024, unique=True, verbose_name='Ссылка на профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Брокер',
                'verbose_name_plural': 'Брокеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='Ссылка на объявление')),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Агентство')),
                ('agency_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на агентство')),
                ('status', models.CharField(choices=[('New', 'Новая ссылка'), ('Done', 'Обработано'), ('Error', 'Ошибка'), ('Broker Info Done', 'Собрана инф. о брокере')], default='New', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_app.broker', verbose_name='Брокер')),
            ],
            options={
                'verbose_name': 'Объявление (LoopNet)',
                'verbose_name_plural': 'Объявления (LoopNet)',
                'ordering': ['id'],
            },
        ),
    ]
