# Generated by Django 5.2.3 on 2025-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='awards',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
    ]
