# Generated by Django 5.2.3 on 2025-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_broker_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='company_bio',
            field=models.TextField(blank=True, null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='broker',
            name='company_website',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='broker',
            name='licenses',
            field=models.TextField(blank=True, null=True, verbose_name='Лицензии'),
        ),
        migrations.AddField(
            model_name='broker',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Профиль LinkedIn'),
        ),
    ]
