# Generated by Django 5.2.3 on 2025-06-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_broker_company_bio_broker_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='company_bio',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='licenses',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='linkedin_url',
        ),
    ]
